[install]
# Use exact versions for dependencies
exact = true

[debug]
# Enable source maps for better debugging
sourcemap = true

[build]
# Build configuration
target = "node"
minify = false
sourcemap = true 